default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  password: <%= ENV["DATABASE_PASSWORD_LOCAL"] %>
  username: <%= ENV["DATABASE_USER_LOCAL"] %>
  host: <%= ENV["DATABASE_HOST_LOCAL"] %>
  port: <%= ENV['DB_PORT'] %>

development:
  <<: *default
  database: <%= ENV["DATABASE_NAME_DEV"] %>

test:
  <<: *default
  database: <%= ENV["DATABASE_NAME_TEST"] %>

production:
  <<: *default
  database: <%= ENV["DATABASE_NAME_PRODUCTION"] %>
  username: event_system
  password: <%= ENV["EVENT_SYSTEM_DATABASE_PASSWORD"] %>
